# Generated by Django 4.2.4 on 2023-09-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_prescriptivecart_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptivecart',
            name='approve',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Processing', 'Processing'), ('Declined', 'Declined')], default=('Declined', 'Declined'), max_length=50),
        ),
    ]
