# Generated by Django 4.2.4 on 2023-09-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_orders_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='orders',
            name='review',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Dispatched'), (3, 'Out For Delivery'), (4, 'Delivered'), (5, 'Declined')], default=1),
        ),
    ]
