# Generated by Django 4.2.4 on 2023-09-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_refund_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='noofSales',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='markedprice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sellingprice',
            field=models.IntegerField(),
        ),
    ]
