# Generated by Django 4.2.4 on 2023-09-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_guestqty_guestproducts_guest_actualproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestproducts',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
