# Generated by Django 4.2.4 on 2023-09-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_summary_alter_guest_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='guestuser',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='summary',
            name='registered_user',
            field=models.IntegerField(default=0),
        ),
    ]
