# Generated by Django 4.2.4 on 2023-09-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_orders_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
