# Generated by Django 4.2.4 on 2023-10-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_refund_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('weight', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=250)),
                ('landmark', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created_at'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='guestproducts',
            options={'verbose_name': 'GuestProduct', 'verbose_name_plural': 'GuestProducts'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('-updated_at',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='prescriptivecart',
            options={'verbose_name': 'PrescriptiveCart', 'verbose_name_plural': 'PrescriptiveCart'},
        ),
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name': 'Summary', 'verbose_name_plural': 'Summary'},
        ),
    ]
