# Generated by Django 4.2.4 on 2023-10-28 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_guest_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Cart', 'verbose_name_plural': 'Cart'},
        ),
    ]
