# Generated by Django 4.2.4 on 2024-01-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_personalinfo_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ratings',
            field=models.FloatField(default=4),
        ),
    ]
