# Generated by Django 4.2.4 on 2023-09-14 13:57

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=app.models.getCategoryFileName)),
                ('description', models.TextField(max_length=150)),
                ('statusHide', models.BooleanField(default=False, help_text='1-hide , 0-display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ProductImage', models.ImageField(upload_to=app.models.getProductFileName)),
                ('description', models.TextField(max_length=150)),
                ('purpose', models.TextField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('statusHide', models.BooleanField(default=False, help_text='1-hide , 0-display')),
                ('superbadge', models.CharField(blank=True, choices=[('Trending', 'Trending'), ('New Arrivals', 'New Arrivals'), ('Top Selling', 'Top Selling')], max_length=50, null=True)),
                ('markedprice', models.FloatField()),
                ('sellingprice', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ratings', models.IntegerField(default=0)),
                ('category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
