# Generated by Django 4.2.4 on 2023-09-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_image_prescriptivecart_prescriptionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptivecart',
            name='approve',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Processing', 'Processing'), ('Declined', 'Declined')], default=('Processing', 'Processing'), max_length=50),
        ),
    ]
