# Generated by Django 4.2.4 on 2023-09-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (2, 'Dispatched'), (3, 'Out For Delivery'), (4, 'Delivered'), (5, 'Declined')], default=1, max_length=50),
        ),
    ]
