# Generated by Django 4.2.4 on 2023-09-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_orders_options_orders_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='review',
            field=models.BooleanField(default=False),
        ),
    ]
