# Generated by Django 4.2.4 on 2023-09-19 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0017_orderitems_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refundupi', models.CharField(max_length=50)),
                ('refundAmount', models.IntegerField()),
                ('reason', models.TextField(max_length=250)),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
