# Generated by Django 4.2.4 on 2023-09-19 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orders', unique=True),
        ),
    ]
