# Generated by Django 4.2.4 on 2023-09-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_guest_guestqty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GuestQty',
            new_name='GuestProducts',
        ),
        migrations.AddField(
            model_name='guest',
            name='actualproducts',
            field=models.IntegerField(default=0),
        ),
    ]
