# Generated by Django 4.2.4 on 2023-09-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_summary_guestuser_summary_registered_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-noofSales',)},
        ),
        migrations.AddField(
            model_name='summary',
            name='cash',
            field=models.IntegerField(default=0),
        ),
    ]
