# Generated by Django 4.2.4 on 2023-10-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_personalinfo_options_orders_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='contact',
            field=models.CharField(default='9952414562', max_length=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
