# Generated by Django 4.2.4 on 2023-10-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_guest_contact_alter_orders_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
